### ISSUE TITLE
Comments and other shortcuts.

### ISSUE THREAD

**Issue by Falven** [thenewvu/SublimeCMakeEditor#3]
Toggling comments does not work on files with CMakeEditor Syntax.
⌘+/ On the mac,
CTRL+/ On windows.

**Comment by Falven** [comment]
Actually, almost none of the shortcuts work including selections. (Expand selection to line...)

**Comment by thenewvu** [comment]
Thank @Falven. I or some contributor (appreciate!) will fix this in the next version, maybe in this weekend.
